[package]
name = "commons"
version = "0.1.0"
edition = "2021"
description = "Common libraries for DLMM"
authors = ["tian <tian@racoons.dev>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anchor-client = { workspace = true, features = ["async"] }
anyhow = { workspace = true }
lb_clmm = { path = "../programs/lb_clmm", features = ["cpi"] }
tokio = { workspace = true, features = ["full", "parking_lot"] }
bincode = "1.3.3"
