[package]
name = "lb_clmm"
<<<<<<< HEAD
version = "0.8.0"
=======
version = "0.7.0"
>>>>>>> 19dbfda (feat: token 2022 + bump anchor to 0.29.0 to support extension type)
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "lb_clmm"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
localnet = []
alpha-access = []
test-bpf = []
staging = []

[dependencies]
anchor-lang = { version = "0.29.0", features = ["event-cpi"] }
anchor-spl = "0.29.0"
uint = "0.8.5"
bytemuck = { version = "1.13.1", features = ["derive", "min_const_generics"] }
ruint = "1.3.0"
num-traits = "0.2.16"
num-integer = "0.1.45"
mpl-token-metadata = "3.0.1"
solana-program = "1.16.0"
num_enum = "0.7.1"

[dev-dependencies]
proptest = "1.2.0"
rand = "0.7.3"
solana-program-test = "1.16.0"
solana-sdk = "1.16.0"
async-trait = "0.1.52"
assert_matches = "1.5.0"
