name: Lb Clmm Cli

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_CLI_VERSION: 1.16.1
  NODE_VERSION: 18.14.2
  ANCHOR_CLI_VERSION: 0.28.0

jobs:
  cli_changed_files:
    runs-on: ubuntu-latest
    outputs:
      cli: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            cli

  cli_build:
    runs-on: ubuntu-latest
    needs: cli_changed_files
    if: needs.cli_changed_files.outputs.cli == 'true'
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: ./.github/actions/setup-anchor
      # Install rust + toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      - run: cargo build -p cli
        shell: bash
