name: Lb Clmm SDK

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_CLI_VERSION: 1.16.13
  NODE_VERSION: 18.14.2
  ANCHOR_CLI_VERSION: 0.28.0

jobs:
  sdk_changed_files:
    runs-on: ubuntu-latest
    outputs:
      sdk: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            ts-client
            artifacts

  sdk_test:
    runs-on: ubuntu-latest
    needs: sdk_changed_files
    if: needs.sdk_changed_files.outputs.sdk == 'true'
    env:
      RPC: ${{ secrets.RPC }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      - uses: ./.github/actions/setup-anchor
      # Install rust + toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - uses: pnpm/action-setup@v4
        with:
          version: 10
      # Cache node_modules
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: ./ts-client/node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml') }}
      - run: anchor build -- --features localnet
        shell: bash
      - run: anchor localnet -- --features localnet & sleep 2
        shell: bash
      - run: cd ts-client && pnpm install && pnpm run test
        shell: bash
