name: DLMM Commons

on:
  pull_request:
    branches:
      - main

jobs:
  common_changed_files:
    runs-on: ubuntu-latest
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            commons
            artifacts

  common_test:
    runs-on: ubuntu-latest
    needs: common_changed_files
    if: needs.common_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v2
      # Install rust + toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.76.0
          override: true
          components: clippy
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      - run: cargo t -p commons --test '*'
        shell: bash
